name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake g++ \
            libboost-system-dev \
            libspdlog-dev \
            protobuf-compiler libprotobuf-dev \
            catch2

      - name: Configure
        run: cmake --preset linux-debug

      - name: Build
        run: cmake --build --preset linux-debug --parallel 2

      - name: Test
        run: ctest --test-dir build/linux-debug --output-on-failure
